### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=drama

### Crear una película
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 120,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ], 
    "rate": 5
}

### Actualizar una película
PATCH http://localhost:1234/movies/aa391090-b938-42eb-b520-86ea0aa3917b
Content-Type: application/json

{
    "id": 1,
    "title": "Hola mundo",
    "year": "2003"
}

